# 相机配置
camera:
  device_id: 0
  width: 1920
  height: 1080
  fps: 30

# 网络配置
network:
  tcp:
    port: 8080
    ip: "127.0.0.1"
  udp:
    port: 8081
    ip: "127.0.0.1"

# 推理配置
inference:
  model_path: "../models/model.engine"
  batch_size: 1
  threshold: 0.5

# 显示配置
display:
  width: 1280
  height: 720
  fps: 30

# 线程配置
thread:
  sleep_ms: 1

# 日志配置
log:
  path: "../logs/"
  level: "debug"
  enable_console: true 