# 默认配置文件
version: 1.0.0
env: "default"

# 相机配置
camera:
  device_id: 0
  width: 1920
  height: 1080
  fps: 30
  exposure: -6
  gain: 10

# 网络配置
network:
  tcp:
    port: 8080
    ip: "127.0.0.1"
    max_connections: 5
  udp:
    port: 8081
    ip: "127.0.0.1"
    buffer_size: 65536

# 推理配置
inference:
  model_path: "../models/model.engine"
  batch_size: 1
  threshold: 0.5
  nms_threshold: 0.45
  class_names: ["class1", "class2", "class3"]
  enable_tensorrt: true

# 显示配置
display:
  width: 1280
  height: 720
  fps: 30
  show_fps: true
  show_detection: true
  font_size: 12
  line_thickness: 2

# 线程配置
thread:
  sleep_ms: 1
  priority_high: true
  stack_size: 0

# 日志配置
log:
  path: "../logs/"
  level: "debug"
  enable_console: true
  max_size: 10485760  # 10MB
  max_files: 10
  flush_interval: 3 